### ISSUE TITLE
Folders, albums etc.. view as list instead of grids... that might simplify UI a lot if there is no album artwork

### ISSUE THREAD

**Issue by nrudnyk** [flaviotordini/musique#20]

**Comment by flaviotordini** [comment]
If there is no album artwork probably metatags should be fixed.

**Comment by hottwaj** [comment]
I think a list view would be really useful so that (if you want) you can:

- see songs in a list (with album, artist track info etc)
- see search results in a list (otherwise if you search for a song name and have the same song by multiple artists, you have to click each item in the grid to see additional detail so you can work out which one you want)
